language: ruby
rvm:
  - 2.4
script:
  - bundle exec rake db:create
  - bundle exec rspec && CODECLIMATE_REPO_TOKEN=15e7cf308823a1e91179870686b8b4778527c1374fd54d015926861713c9fdca bundle exec codeclimate-test-reporter
  - bundle exec rake spec
services:
  - postgresql
